### 1. 주문 생성
POST http://localhost:8082/api/v1/orders
Authorization: Bearer jwt_token_string
Content-Type: application/json
Accept: application/json

{
  "receiverId": "22222222-2222-2222-2222-222222222222",
  "deliveryAddress": "서울특별시 강남구 삼성동",
  "items": [
    {
      "productId": "44444444-4444-4444-4444-444444444444",
      "orderItemAmount": 2
    },
    {
      "productId": "55555555-5555-5555-5555-555555555555",
      "orderItemAmount": 1
    }
  ]
}