### 1. 업체 생성
POST http://localhost:8087/api/v1/companies
Authorization: Bearer jwt_token_string
Content-Type: application/json
Accept: application/json

{
  "companyName": "새우깡 제조회사",
  "companyAddress": "청주",
  "companyType": "SUPPLIER",
  "hubId": "22222222-0d12-45ab-bbd2-9f1baf001234",
  "companyManagerId": 419
}