spring:
  application:
    name: hub-service

  datasource:
    url: jdbc:postgresql://localhost:5432/babko
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update


server:
  port: 8086

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

naver:
  api:
    client-id: "gsvvhkp9nc"
    client-secret: "tta5CdMXf29b4hz0Edsnav1gIb64pIwWODSCLpZx"