### 1. 상품 생성
POST http://localhost:8080/api/v1/products
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI0Iiwicm9sZSI6IlJPTEVfQ09NUEFOWSIsImlhdCI6MTc0Mjg3Mzk4MSwiZXhwIjoxNzQyODc3NTgxfQ.5Wc4xh75pgqr34GK6TE6Zj29rk_OCQlWiVx_MQ4smrRP8RrmedVa0-KVnIeL7azeKZDOKATZ8bSMfm68e7GecA
Content-Type: application/json
Accept: application/json


{
  "productName": "먹태깡",
  "productPrice": 10000,
  "productQuantity": 200,
  "companyId": "f5844081-d854-438e-96dc-93e272dd9376"
}