### 1. 상품 재고 변경
PUT http://localhost:8081/api/v1/inventories
Authorization: Bearer jwt_token_string
Content-Type: application/json
Accept: application/json

{
  "productId": "{productId}",
  "productQuantity": 777
}