### 1. 상품 재고 변경
PUT http://localhost:8081/api/v1/inventories
Authorization: Bearer jwt_token_string
Content-Type: application/json
Accept: application/json

{
  "productId": "2e498308-a1c3-4224-9922-105a4770b53d",
  "productQuantity": 777
}