spring:
  application:
    name: delivery-service

server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

order:
  service:
    url: http://localhost:8082

user:
  service:
    url: http://localhost:8084

hub:
  service:
    url: http://localhost:8086